apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: martingregor/ambulance-ufe
  newName: martingregor/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260317.1348 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
